<?php


function elib_block_newbooks_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    return array(
      'account' => array(
        'info' => t('Last Loans'),
        'cache' => BLOCK_NO_CACHE,
      ),
    );
  }
  elseif ($op == 'view' && $delta == 'account') {
    //global $user;
    $block = array();

    elib_client()->setLibrary(variable_get('elib_retailer_id', ''));

    $response = elib_client()->getLatestLoans();

    module_load_include('client.inc', 'ting');
    foreach($response as $isbn){
      $out .= elib_displaybookNEW(publizon_ting_find_object($isbn),'','small');
    }

    $block['subject'] = t('Top 5 mest lånte');
    $block['content'] = $out;

    return $block;
  }

}

