<?php

/**
 * Implements hook_menu().
 */
function netsound_cart_menu() {
  $items = array();

  $items['ting/object/%/huskeliste'] = array(
    'title' => t('Tilføj til huskeliste'),
    'page callback' => 'netsound_cart_modify',
    'page arguments' => array(2, 'add'),
    'access arguments' => array('access content'),
  );
  
  $items['ting/object/%/huskeliste/fjern'] = array(
    'title' => t('Fjern fra huskeliste'),
    'page callback' => 'netsound_cart_modify',
    'page arguments' => array(2, 'delete'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Modify the contents of a given users netsound cart.
 * 
 * @global object $user
 *  Currently logged in global user object.
 * @param type $ting_object_id
 *  Ting datawall object id.
 * @param type $op 
 *  Operation to preform on the cart. 
 *  
 */
function netsound_cart_modify($ting_object_id, $op) {
  global $user;

  // If the current user is valid and logged in.
  if ($user->uid != 0) {
    // Load the ting client to make request to the datawell.
    module_load_include('client.inc', 'ting');
    $object = ting_get_object_by_id($ting_object_id);
    
    // Check that we got a ting object
    if ($object instanceof TingClientObject) {
      $params = array(
          'uid' => $user->uid,
          'ting_object_id' => $object->id,
      );
      switch ($op) {
        case 'add':
          $params['tstamp'] = time();
          drupal_write_record('netsound_cart', $params);
          drupal_set_message(t('!book er nu tilføjet din huskeliste', array('!book' => l($object->title, 'ting/object/' . $object->id))));
          break;
        
        case 'delete':
          db_query('DELETE FROM {netsound_cart} 
                          WHERE uid = %s 
                            AND ting_object_id = "%s"', $user->uid, $object->id);
          drupal_set_message(t('!book er nu fjernet fra din huskeliste', array('!book' => l($object->title, 'ting/object/' . $object->id))));
          break;
      }
      
      drupal_goto();
    }
    
    // @TODO: What if its not an ting object ?  
  }
}

/**
 * Creates a add to cart link.
 * 
 * @param type $ting_object_id
 * @return type 
 */
function netsound_cart_add_link($ting_object_id) {
  $uri = 'ting/object/' . $ting_object_id . '/huskeliste';
  $options = array(
    'query' => drupal_get_destination(), 
    'attributes' => array(
      'class' => 'addtocart'
    )
  );
  return l(t('Tilføj til huskeliste'), uri, $options);
}

/**
 * Implements hook_block().
 * 
 * Provides the "My lists" block with information about the books placed in the
 * cart.
 * 
 * @TODO implement cache for this list.
 */
function netsound_cart_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('What\'s in my cart?');
      break;

    case 'view':
      // Get current logged in user. 
      global $user;

      // Set default block title.
      $block['subject'] = t('Min huskeliste');

      // Load the ting client.
      module_load_include('client.inc', 'ting');

      $rows = array();
      $result = db_query('SELECT DISTINCT ting_object_id 
                                     FROM {netsound_cart} 
                                    WHERE uid = %d', array('%d' => $user->uid));
      while ($row = db_fetch_array($result)) {
        $object = ting_get_object_by_id($row['ting_object_id']);
        $rows[] = elib_displaybookNEW($object, '', 'small_rm');
      }
      
      if (empty($rows)) {
        $block['content'] = t('Der er ingen bøger på din huskeliste');
      }
      else {
        $block['content'] = implode($rows);
      }
      
      break;
  }
  return $blocks;
}
