<?php

/**
 * Implementation of hook_init.
 */
function ebog_preview_init() {
  /**
   * @todo: This JS is add to all pages on the site (WTF!!!!!!).
   */
  drupal_add_js(drupal_get_path('module', 'ebog_preview') . '/js/ebog_preview_scripts.js');
}

/**
 * Implementation of hook_menu.
 */
function ebog_preview_menu() {
  $menu = array();

  $menu['publizon/%/sample/preview'] = array(
    'title' => 'Preview ting ebook',
    'description' => 'Provide an ebook preview using Monocle.',
    'page callback' => 'ebog_preview_preview',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Get teaser link for a given product based on ISBN number.
 *
 * @param string $isbn
 *  The ebooks ISBN number.
 */
function ebog_preview_preview($isbn) {
  // Default response.
  $response = array(
    'status' => 'err',
    'msg' => t('Book not found.')
  );

  // Try to get product from Publizon.
  try {
    $product = new PublizonProduct($isbn);
    $response = array(
      'status' => 'dl',
      'msg' => $product->teaser_link);
  }
  catch (Exception $e) {
    $response = array(
      'status' => 'err',
      'msg' => $e->getMessage());
  }

  echo json_encode($response);
  exit(0);
}
