<?php
/**
 * @file
 *
 * Ebog download main module file.
 *
 * Provides extended download workflow for ebooks.
 */

/**
 * Implementation of hook_init.
 */
function ebog_download_init() {
  /**
   * @todo: This JS is add to all pages on the site (WTF!!!!!!).
   */
  $path = drupal_get_path('module', 'ebog_download');

  drupal_add_js($path . '/js/ebog_download_scripts.js', 'file');
  drupal_add_js($path . '/js/jquery.form.js', 'file');
  drupal_add_css($path . '/css/ebog_download_style.css', 'file');
  jquery_ui_add(array('ui.dialog', 'ui.draggable'));
  jquery_ui_theme_load();
}

/**
 * Implementation of hook_menu.
 */
function ebog_download_menu() {
  $menu = array();

  $menu['ting/object/%/download/request'] = array(
    'title' => 'Download ting ebook',
    'description' => 'Checker for download abilities regarding selected ebook for specific user.',
    'page callback' => 'ebog_download_loan_initial',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $menu['ting/object/%/download/popup'] = array(
    'title' => 'Show a popup before download',
    'description' => 'Display some user specific text and perform some check before download.',
    'page callback' => 'ebog_download_loan_popup',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Implementation of hook_theme.
 */
function ebog_download_theme($existing, $type, $theme, $path) {
  $hooks = array();

  $hooks['ebog_download_checkboxes'] = array(
    'arguments' => array('data' => NULL),
    'template' => 'templates/ebog_download-checkboxes',
  );

  $hooks['ebog_download_error'] = array(
    'arguments' => array('data' => NULL),
    'template' => 'templates/ebog_download-error',
  );

  $hooks['ebog_download_info'] = array(
    'arguments' => array('data' => NULL),
    'template' => 'templates/ebog_download-info',
  );

  return $hooks;
}

/**
 * Provides item loan/check routine for elib service.
 *
 * @global $user
 *   Logged in user data
 * @param $ting_id
 *   Ting object id
 */
function ebog_download_loan_initial($ting_id) {
  global $user;
  $status = array();

  // Whether user authenticated in drupal
  if ($user->uid) {
    $isbn = elib_get_isbn_from_object_id($ting_id);
    $ean = convertToEAN($isbn);

    $userinfo = elib_user_get_cred();
    $client = elib_client();
    $client->setLoaner($userinfo['cpr'], $userinfo['pin'], $userinfo['lib']);

    $book = $client->getBook($ean);
    $down_link = get_download_url(elib_user_get_loans(), $ean);

    // Whether book fetched well
    if ((int)$book->status->code == 101) {
      if (is_string($down_link)) {
        if ($down_link != '') {
          $status = array(
            'status' => TRUE,
            'title' => t('Success'),
            'content' => theme('ebog_download_info', array('message' => t('Book download url.'), 'link' => $down_link))
          );
        }
        else {
          $status = array(
            'status' => FALSE,
            'title' => t('Error'),
            'content' => theme('ebog_download_error', array(
              'message' => t('Failed to fetch download url.'))
            )
          );
        }

      }
      else {
        $loan = elib_client()->makeLoan($ean);
        // Whether book loaned well
        if ((int)$loan->status->code == 101) {
          // Clear loans cache for the user.
          elib_user_clear_loans_cache($user->uid);

          $down_link = $loan->data->downloadurl;
          $status = array(
            'status' => TRUE,
            'title' => t('Success'),
            'content' => theme('ebog_download_info', array('message' => t('Successfuly loaned this item.'), 'link' => $down_link))
          );
        }
        else {
          $status = array(
            'status' => FALSE,
            'title' => t('Error'),
            'content' => theme('ebog_download_error', array(
              'message' => t('@message', array('@message' => $loan->status->message)))
            )
          );
        }
      }
    }
    else {
      $status = array(
        'status' => FALSE,
        'title' => t('Error'),
        'content' => theme('ebog_download_error', array(
          'message' => t('@message', array('@message' => $book->status->message)))
        )
      );
    }
  }
  else {
    $status = array(
      'status' => FALSE,
      'title' => t('Error'),
      'content' => theme('ebog_download_error', array('message' => t('Only authenticated users are able to loan.')))
    );
  }

  // Send response
  drupal_json($status);
  exit(0);
}

/**
 * Fetch specific book download url.
 *
 * @param SimpleXMLElement $loans
 *   User loans object
 * @param String $ean
 *   Searched item isbn
 * @return String
 *   Download url
 */
function get_download_url($loans, $ean) {
  if ($loans instanceof SimpleXMLElement) {
    foreach ($loans->orderitem as $book) {
      if ($book->book['id'] == $ean && !elib_user_is_loan_expired($book)) {
        return (string)$book->data->data->downloadurl;
      }
    }
  }
  return FALSE;
}

/**
 * More a dummy method, used only for confirmation dialog retrieval.
 *
 * @param $ting_id
 *   Ting object id.
 */
function ebog_download_loan_popup($ting_id) {
  global $user;
  $status = array();

  // Whether user is logged in.
  if ($user->uid) {
    $user_agent = $_SERVER['HTTP_USER_AGENT'];
    $reader = t('Adobe Digital Edition');
    // android - Aldiko Book Reader
    // iPod, iPad, iPhone - Bluefire Reader
    // else - Adobe PDF reader
    if (preg_match('/android/i', $user_agent)) {
      $reader = t('Aldiko Book Reader');
    }
    elseif (preg_match('/(iPod)|(iPad)|(iPhone)/i', $user_agent)) {
      $reader = t('Bluefire Reader');
    }

    $status = array(
      'title' => t('Download ebog'),
      'content' => theme('ebog_download_checkboxes', array('reader' => $reader)),
    );
  }
  else {
     // User was not logged in, so present login form.
    $form = drupal_get_form('elib_popup_login_form');
    $status = array(
      'status' => 'login',
      'title' => t('Login'),
      'content' => $form,
    );
  }

  drupal_json($status);
  exit(0);
}

/**
 * Build popup login form based on the user_login in form used to login normally
 * and overrides the validation functions.
 *
 * @return array $form.
 */
function elib_popup_login_form() {
  $form_id = 'user_login';
  $form_state = array();

  // Get user login form.
  $form = call_user_func_array('drupal_retrieve_form', array($form_id));

  // Run hook_form_alter functions.
  $hook = 'form_alter';
  foreach (module_implements($hook) as $module) {
    $function = $module . '_' . $hook;
    $function($form, $form_state, $form_id);
  }

  // Override validate function.
  $form['#validate'][0] = 'elib_popup_login_form_validate';

  return $form;
}

/**
 * Form validation for popup login form, which returns json.
 */
function elib_popup_login_form_validate($form, &$form_state) {
  // Default status message.
  $status = array(
    'status' => FALSE,
    'title' => t('Error'),
    'content' => '<div class="messages error">' . t('Sorry, unrecognized username or password. <a href="@password">Have you forgotten your password?</a>', array('@password' => url('user/password'))) . '</div>',
  );

  // If no credentials are presented, return.
  if (empty($form_state['values']['name']) || empty($form_state['values']['pass'])) {
    drupal_json($status);
    exit(0);
  }

  // The user may use both borrower card / cpr number to login, so we have to
  // remove anything thats not an number form the user name.
  $card = preg_replace('/\D+/', '', $form_state['values']['name']);

  // Try to login to the library, this will create the user if login succeed
  // and the user do not exists in Drupal.
  $account = elib_check_credentials($card, $form_state['values']['pass'], $form_state['values']['library']);
  if ($account) {
    global $user;
    $user = $account;
    user_authenticate_finalize($form_state['values']);
    $status = array(
      'status' => 'loggedin',
      'title' => t('Login'),
      'content' => t('You are now logged in an can procceed'),
    );
  }

  drupal_json($status);
  exit(0);
}