<?php 


function elib_block_lastloans_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
	  $blocks[0]['info'] = t('Last loans');
	  $blocks[1]['info'] = t('Newest books');
	  $blocks[2]['info'] = t('Popular books books');
	  $blocks[3]['info'] = t('Welcome block - my page');
	  $blocks[4]['info'] = t('dummyblock2 books');
	  $blocks[5]['info'] = t('Logout block button');
      $blocks[6]['info'] = t('Popular books extended');
	  return $blocks;
  }
  elseif ($op == 'view') {
    //global $user;
    $block = array();
    
    elib_client()->setLibrary(variable_get('elib_retailer_id', ''));
    
    module_load_include('client.inc', 'ting');
    
    switch($delta){
    	case 0:
    		
		    $response = elib_client()->getLatestLoans();  
		    
		    
		    foreach($response as $isbn){
		      $out .= elib_displaybookNEW(ting_get_object_by_isbn($isbn),'','small'); 
		    }
		    $block['subject'] = t('Seneste Lån');	
    		break;
    	case 1:
    		$response = elib_client()->getNewBooks();
    		
    		
    		//var_dump($response);
    		   		
    		
	    		foreach($response->data->toplistitem as $item){
	    			
	    		  $isbn = trim($item->ebookid);
	    		  $title = (trim($item->title));
	    		  
	    		  //krumo(array($isbn,$title));
	    		  
	    		  if(ting_get_object_by_isbn($isbn)){
	    		    $toplist[] = $isbn;
	    		  //  krumo('hurray'.$isbn);
	    		  }
	    		  if(sizeof($toplist) == 5){
	    		    break;
	    		  }
	    		}
	    		if(is_array($toplist)){  
  	    		foreach($toplist as $isbn){
  	    		 	$out .= elib_displaybookNEW(ting_get_object_by_isbn($isbn),'','small'); 
  	    		}
	    		}
    		  $block['subject'] = t('Nyeste bøger');
    		break;
    	case 2:
          $cache_name = 'elib_popular_books_cache' . $delta;
          $cache_table = 'cache';

          $cache = cache_get($cache_name, $cache_table);
          $out = '';
          
          if (isset($cache->data)) {
            $out = $cache->data;
          }
          else {
            $response = elib_client()->getPopularBooks();
            $index = 1;

            foreach ($response->data->toplistitem as $item) {
              //print $item['ebookid'].'--';
              if (ting_get_object_by_isbn(trim($item->ebookid))) {
                $out .= elib_displaybookNEW(ting_get_object_by_isbn(trim($item->ebookid)), array('popular' => 1), 'small', $index, $item);
                $index++;
              }
            }

            cache_set($cache_name, $out, $cache_table, strtotime('+1 day'));
          }

          if($out == '') {
            $out = '<h1>';
            $out .= t('There is currently no popular items.');
            $out .= '</h1>';
          }
          else {
            $out .= '<p class="popular-more"><a href="/popular">' . t('See more') . '</a></p>';
          }

          $block['subject'] = t('populære bøger');
          break;
      case 3:
        global $user;
        if($user->uid == 0){return false;}    		
        
        $u = elib_user_get_cred();
        $libs = elib_libraries_get_libraries();
                
        foreach ($libs as $key => $lib){
        	if($key == $u['lib']){
        		$library = $lib;
        	}
        }
        if(!$library){
        	return;
        }
        $out = '<p class="spacing-before">'.t('Velkommen! Som bruger i %library kan du låne %amount om måneden',array('%library' => $library,'%amount' => format_plural(elib_libraries_get_maxloans($u['lib']), 'en ebog', '@count ebøger'))).'</p>';

        elib_client()->setLoaner($u['cpr'],$u['pin'],$u['lib']);
        $loans = elib_client()->getLoans();
        $loans = $loans->orderitem;
        $loanlimit = 100000000000;
        if($loans){
          $nob = sizeof($loans);
          if($nob >= elib_libraries_get_maxloans($u['lib'])){
          	
            foreach($loans as $obj){
      
            	if($loanlimit > elib_str_to_time($obj->loanexpiredate,true)){
				        $loanlimit = elib_str_to_time($obj->loanexpiredate,true);
				      }
            }
          	
            $diff = $loanlimit-time();
            $days = floor($diff/86400);
      
            $rest = $diff % 86400;
      
            $hours = floor($rest/3600);
            
            $out .= t('<p style="text-align:right;margin-top:10px;">Du kan låne en ebog igen om %dage og %time</p>', array('%dage' => format_plural($days, 'en dag', '@count dage'),'%time' => format_plural($hours, 'en time', '@count timer')));
          }
        }
        
        
    		break;
    	case 5:
    		global $user;
    		$block['subject'] = t('Min profil');
    		if($user->uid){
    			$out = '<p>Du er logget ind: '.l('Log ud','logout',array('attributes' => array('class' => 'biglogoutbutton'))).'</p>';
    		}
    		break;

        case 6:
          drupal_add_css(drupal_get_path('elib_block_lastloans', 'module') . '/css/elib_popular.css', 'file');

          $cache_name = 'elib_popular_books_extended_cache' . $delta;
          $cache_table = 'cache';

          $cache = cache_get($cache_name, $cache_table);
          $out = '';

          if (isset($cache->data)) {
            $out = $cache->data;
          }
          else {
            $response = elib_client()->getPopularBooks(25);
            $page = 0;
            $items = 1;
            
            foreach ($response->data->toplistitem as $item) {
              if ($items % 11 == 0) {
                $page++;
                $items = 1;
              }
              
              $isbn = trim($item->ebookid);
              $ting_object = ting_get_object_by_isbn($isbn);
              if ($ting_object) {
                $out[$page] .= theme('elib_item', array(
                    'ting_obj' => $ting_object,
                    'isbn' => $isbn,
                  )
                );
              }

              $items++;
            }

            //cache_set($cache_name, $out, $cache_table, strtotime('+1 day'));
          }

          //var_dump($out);

          if($out == '') {
            $out = '<h1>';
            $out .= t('There are currently no popular items.');
            $out .= '</h1>';
          }
          else {
            $out = theme('elib_popular', array(
              'elib_popular' => $out[0])
            );
          }

          $block['subject'] = t('100 populære bøger');
    }
    
    //krumo($books);
    
    //$response = elib_client()->getNewBooks();
    
 
    
      
      $block['content'] = $out;

    
    
    return $block;
  }
  
}

/**
 * Implements hook_theme().
 */
function elib_block_lastloans_theme($existing, $type, $theme, $path) {
  $hooks = array();

  $hooks['elib_item'] = array(
    'arguments' => array('data' => NULL),
    'template' => 'templates/elib_item',
  );

  $hooks['elib_popular'] = array(
    'arguments' => array('data' => NULL),
    'template' => 'templates/elib_popular',
  );

  return $hooks;
}















?>
