<?php

function netsound_menu_alter(&$items){
  unset($items['user/password']);
  unset($items['user/register']);
}

function netsound_menu(){
  $items = array();
  $items['admin/settings/netsound'] = array(
    'title' => 'Netsound settings',
    'description' => 'settings for Netsound',
    'access arguments' => array('access administration pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('netsound_settings_form'),
    'file' => 'netsound.admin.inc',
  );
  return $items;
}

function netsound_block($op = 'list', $delta = 0, $edit = array()) {
  $blocks = array();
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Genre: Keywords'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[1] = array(
      'info' => t('Genre: Categories'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[2] = array(
      'info' => t('FAQ BLOCK'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[3] = array(
      'info' => t('Zero Search top'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[4] = array(
      'info' => t('Shortcut menu'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[5] = array(
      'info' => t('Contact ELIB'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[6] = array(
      'info' => t('Contact NETLYD'),
      'cache' => BLOCK_NO_CACHE,
    );
    $blocks[7] = array(
      'info' => t('Form: Error in ebook title'),
      'cache' => BLOCK_NO_CACHE,
    );
  }
  elseif ($op == 'view') {
    switch($delta){
      case 0:
        $blocks['subject'] = t('Keywords');
        $keywords = explode(',',variable_get('netsound_keywords', ''));
        if(is_array($keywords)){
          foreach($keywords as $keyword){
            $keyword = trim($keyword);
            $linked[] = l($keyword,'ting/search/'.$keyword);
          }
          $blocks['content'] = '<ul><li> '. implode("</li><li>",$linked) .'</li></ul>';
        }
        break;

      case 1:
        //$block['subject'] = t('Categories');
        //$block['content'] = 'dflksæfd';
        break;

      case 2:
        $content .= faq_page(arg(1));
        $blocks['content'] = $content;
        break;

      case 3:
        drupal_set_message('<p style="strong">'.t('Din søgning på <strong>!query</strong> gav ingen resultater. ',array('!query' => strip_tags(arg(1)))).'</p><p>'.t('Hjælp til søgning:<br />- Prøv at bruge synonymer. Du søger måske efter noget, der bruger andre ord. - Gør søgningen mere generel. Prøv mere generelle udtryk i stedet for konkrete udtryk. - Du kan trunkere i eReolen.dk med "". Skriver du "hund", får du resultat på ord som begynder på "hund", altså hund, hundene, hundens osv.').'</p>');
        break;

      case 4:
        $blocks['content'] = drupal_get_form('netsound_shortcutmenu_form');
        break;

      case 5:
        $blocks['content'] = drupal_get_form('netsound_contact_elib_form');
        break;

      case 6:
        $blocks['content'] = drupal_get_form('netsound_contact_netlyd_form');
        break;

      case 7:
        $blocks['content'] = drupal_get_form('netsound_contact_error_form');
        break;
    }
  }

  return $blocks;
}

function netsound_contact_error_form($form_state) {
  $form = array();
  $form['contact_library'] = array(
    '#type' => 'select',
    '#title' => t('Vælg dit bibliotek'),
    '#options' => publizon_get_libraries(),
    '#required' => TRUE,
  );

  $userinfo = publizon_user_get_credentials();
  if ($userinfo) {
    $form['contact_library']['#default_value'] = $userinfo['retailer_id'];
    $form['contact_library']['#disabled'] = TRUE;
  }

  $form['contact_login_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Det nummer du benytter ved login (Lånerkortnr. / CPR)'),
    '#required' => TRUE
  );

  $form['contact_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Hvilken titel/titler drejer det sig om?'),
    '#required' => TRUE
  );

  $form['contact_time'] = array(
    '#type' => 'date',
    '#title' => t('Hvornår oplevede du problemet?'),
    '#required' => TRUE
  );

  $form['contact_error'] = array(
    '#type' => 'textarea',
    '#title' => t('Uddybende beskrivelse af det problem du oplever'),
    '#required' => TRUE,
  );

  $form['tablet'] = array(
    '#type' => 'select',
    '#title' => t('Hvilken enhedstype bruger du?'),
    '#options' => array(
        'pc' => 'PC',
        'smartphone' => 'SmartPhone',
        'tablet' => 'Tablet',
        'ebookreader' => 'Ebogslæser',
    ),
    '#required' => TRUE,
  );

  $form['tablet_model'] = array(
    '#type' => 'textfield',
    '#title' => t('Indtast evt. modelnummer'),
  );

  $form['contact_browser'] = array(
    '#type' => 'select',
    '#title' => t('Hvilken browser anvender du?'),
    '#options' => array(
      'ie11' => 'Internet Explorer 11',
      'ie10' => 'Internet Explorer 10',
      'ie9' => 'Internet Explorer 9',
      'ie8' => 'Internet Explorer 8',
      'ie7' => 'Internet Explorer 7 eller ældre',
      'ff' => 'Mozilla Firefox',
      'safari' => 'Safari',
      'chrome' => 'Google Chrome',
      'opera' => 'Opera',
      'netscape' => 'Netscape',
      'anden' => 'Anden'
    ),
    '#required' => TRUE
  );

  $form['contact_os'] = array(
    '#type' => 'select',
    '#title' => t('Hvilket operativsystem anvender du?'),
    '#required' => TRUE,
    '#options' => array(
      'win8' => 'Windows 8',
      'win7' => 'Windows 7',
      'vista' => 'Windows Vista',
      'winxp' => 'Windows XP',
      'win2k' => 'Windows 2000 eller ældre',
      'osx' => 'MacOS 10 eller nyere',
      'os9' => 'MACOS 9 eller ældre',
      'linux' => 'Linux'
    )
  );

  $form['contact_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Rapporter Fejl')
  );

  $form['#submit'][] = 'netsound_contact_form_submit';

  return $form;
}

function netsound_contact_netlyd_form($form_state){
  $form = array();
   $form['contact_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Navn'),
  );

  $form['contact_mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#required' => TRUE
  );

  $form['contact_library'] = array(
    '#type' => 'select',
    '#title' => t('Vælg dit bibliotek'),
    '#options' => publizon_get_libraries(),
  	'#required' => TRUE,
  );

  $userinfo = publizon_user_get_credentials();
  if ($userinfo) {
    $form['contact_library']['#default_value'] = $userinfo['retailer_id'];
    $form['contact_library']['#disabled'] = TRUE;
  }
  $form['problem'] = array(
    '#type' => 'textarea',
    '#title' => t('Kommentar')
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send besked')
  );
  $form['#submit'][] = 'netsound_contact_form_submit';

  return $form;

}

function netsound_contact_elib_form($form_state){
  $form = array();

  $form['contact_library'] = array(
    '#type' => 'select',
    '#title' => t('Vælg dit lokalbibliotek2'),
    '#options' => publizon_get_libraries(),
  	'#required' => TRUE
  );

  $userinfo = publizon_user_get_credentials();
  if ($userinfo) {
    $form['contact_library']['#default_value'] = $userinfo['retailer_id'];
    $form['contact_library']['#disabled'] = TRUE;
  }


  $form['contact_ssn'] = array(
    '#type' => 'textfield',
    '#title' => t('Det nummer du benytter ved login (Lånerkortnr. / CPR)'),
    '#required' => TRUE,
  );

  $form['contact_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Navn'),
    '#required' => TRUE,
  );

  $form['contact_mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#required' => TRUE
  );

  $form['problem'] = array(
    '#type' => 'textarea',
    '#title' => t('Uddybende beskrivelse af det problem du oplever'),
    '#required' => TRUE,
  );

  $form['book_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Hvilken titel/titler drejer det sig om?'),
    '#required' => TRUE,
  );

  $form['error_time'] = array(
    '#type' => 'date',
    '#title' => t('Hvornår oplevede du problemet?'),
    '#required' => TRUE,

  );

  $form['tablet'] = array(
    '#type' => 'select',
    '#title' => t('Hvilken enhedstype bruger du?'),
    '#options' => array(
        'pc' => 'PC',
        'smartphone' => 'SmartPhone',
        'tablet' => 'Tablet',
        'ebookreader' => 'Ebogslæser',
    ),
    '#required' => TRUE,
  );

  $form['tablet_model'] = array(
    '#type' => 'textfield',
    '#title' => t('Indtast evt. modelnummer'),
  );

  $form['os'] = array(
    '#type' => 'select',
    '#title' => t('Hvilken browser anvender du?'),
    '#options' => array(
      'ie11' => 'Internet Explorer 11',
      'ie10' => 'Internet Explorer 10',
      'ie9' => 'Internet Explorer 9',
      'ie8' => 'Internet Explorer 8',
      'ie7' => 'Internet Explorer 7 eller ældre',
      'ff' => 'Mozilla Firefox',
      'safari' => 'Safari',
      'chrome' => 'Google Chrome',
      'opera' => 'Opera',
      'netscape' => 'Netscape',
      'anden' => 'Anden'
    ),
  );

  $form['contact_os'] = array(
    '#type' => 'select',
    '#title' => t('Hvilket operativsystem anvender du?'),
    '#required' => TRUE,
    '#options' => array(
      'win8' => 'Windows 8',
      'win7' => 'Windows 7',
      'vista' => 'Windows Vista',
      'winxp' => 'Windows XP',
      'win2k' => 'Windows 2000 eller ældre',
      'osx' => 'MacOS 10 eller nyere',
      'os9' => 'MACOS 9 eller ældre',
      'linux' => 'Linux'
    )
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send spørgsmål')
  );
  $form['#submit'][] = 'netsound_contact_form_submit';

  return $form;
}

function netsound_contact_form_submit($form, &$form_state){

  $header = array('Form Key', 'Value');
  $rows = array();

  $libraries = publizon_get_libraries();

  foreach($form_state['values'] as $key => $value){
    // Change library id with real name.
    if ($key == 'contact_library') {
      $value = $libraries[$value];
    }
    $rows[] = array(
      array(
      	'data' => t('mailkey_'.$key),
      ),
      array(
      	'data' => is_array($value) ? implode("-", $value) : $value,
      )
    );
  }
  array_pop($rows);
  array_pop($rows);
  array_pop($rows);
  array_pop($rows);

  $out = theme('table', $header, $rows, $table_attributes);

  $params['subject'] = t('Support besked fra eReolen.dk');
  $params['body'] = $out;


  $mail = variable_get('netsound_elibmail', '');
  if($form_state['values']['form_id'] == 'netsound_contact_netlyd_form'){
    $mail = variable_get('netsound_supportmail', '');
  }
  else if($form_state['values']['form_id'] == 'netsound_contact_error_form'){
    $mail = variable_get('netsound_publizonmail', '');
  }

  $mail_from = $form_state['values']['contact_mail'] == NULL ? "support@ereolen.dk" : $form_state['values']['contact_mail'];
  drupal_mail('netsound','somekey',$mail,language_default(),$params,$mail_from,TRUE);

  drupal_set_message(t('Tak for din henvendelse. Vi stræber på at behandle den hurtigst muligt.'));
  drupal_goto(); // frontpage
}

function netsound_shortcutmenu_form($form_state){
  $form  = array();

  $questions = explode("\n", variable_get('netsound_shortcutmenu', ''));
  if(is_array($questions)){
    foreach($questions as $line){
      list($label,$link) = explode('|',$line);
      $options[] = trim($label);
    }
  }

  $form['shortcut'] = array(
		'#type' => 'radios',
		'#prefix' => '<strong><p>'.t('Drejer din henvendelse sig om et af de følgende punkter?').'</p></strong><p>'.t('Hvis du vælger et af disse punkter istedet for at skrive direkte til os vil ekspeditionstiden være væsentlig kortere. På forhånd tak.').'</p>',
    #'#description' => ,
    '#options' => $options,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Kontakt')
  );
  $form['#submit'][] = 'netsound_shortcutmenu_form_submit';
  return $form;
}

function netsound_shortcutmenu_form_submit($form, &$form_state){
  $questions = explode("\n",variable_get('netsound_shortcutmenu', ''));
  if(is_array($questions)){
    foreach($questions as $line){
      list($label,$link) = explode('|',$line);
      $options[] = url(trim($link));
    }
  }
  drupal_goto($options[$form_state['values']['shortcut']]);
}

function netsound_get_genres_from_categories($tid){
  $sql = '
    SELECT node.nid AS nid,
      content_type_category_genre.field_amount_value AS amount,
      node.type AS node_type,
      node.vid AS node_vid,
      content_type_category_genre.field_searchphrase_value AS searchphrase,
      node.title AS node_title
    FROM node node
    LEFT JOIN content_type_category_genre ON node.vid = content_type_category_genre.vid
    INNER JOIN term_node term_node ON node.vid = term_node.vid
    WHERE term_node.tid = %s
	';
  $rows = array();

  $res = db_query($sql,array('%s' => $tid));
  while($row = db_fetch_array($res)){
    $rows[] = $row;
  }
  return $rows;
}

function netsound_form_alter(&$form, $form_state, $form_id) {

  if($form_id == 'contact_mail_page'){

    $form['mail']['#size'] = 29;
    unset($form['name']);
    unset($form['subject']);
    unset($form['copy']);

  }
}

function netsound_show_videolink($tid){
  $res = db_query('SELECT node.nid AS nid
 FROM node node
 INNER JOIN term_node term_node ON node.vid = term_node.vid
 WHERE (node.type in ("helpvideo")) AND (term_node.tid = '.$tid.')
  ');
  $row =  db_fetch_array($res);
  return node_load($row['nid']);

}

function netsound_mail($key, &$message, $params) {

  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );

  foreach ($headers as $key => $value) {
    $message['headers'][$key] = $value;
  }

  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
}
