<?php

/**
 * @file
 * This module is used to make alterations that is not possible to do form 
 * inside the theme. Such as chaning cacheing header etc.
 * 
 */

/**
 * Set max-age for pages that are cacheable, when not in external cache 
 * mode. This allows us to cache pages in varnish at the same time use
 * Drupal pages cache for https requests.
 */
function ereolen_admin_init(){
  $cache_mode = variable_get('cache', CACHE_DISABLED);
  if (drupal_page_is_cacheable() && $cache_mode != CACHE_EXTERNAL) {
    $max_age = variable_get('page_cache_max_age', 0);
    drupal_set_header('Cache-Control', 'public, max-age=' . $max_age);
  }
}