<?php

/**
 * @file
 * This module is used to make alterations that is not possible to do form
 * inside the theme. Such as chaning cacheing header etc.
 *
 */

/**
 * Set max-age for pages that are cacheable, when not in external cache
 * mode. This allows us to cache pages in varnish at the same time use
 * Drupal pages cache for https requests.
 */
function ereolen_admin_init(){
  $cache_mode = variable_get('cache', CACHE_DISABLED);
  if (drupal_page_is_cacheable() && $cache_mode != CACHE_EXTERNAL) {
    $max_age = variable_get('page_cache_max_age', 0);
    drupal_set_header('Cache-Control', 'public, max-age=' . $max_age);
  }
}

function ereolen_admin_ting_client_request_alter(&$request) {
  if (is_a($request, 'TingClientSearchRequest')) {
    $request->setQuery('( ' . $request->getQuery() . ' ) AND (dc.identifier=978*)');
  }
}

function ereolen_admin_ting_client_response_alter(&$reponse) {
//  if (empty($object_id)) {
//    return FALSE;
//  }
//  module_load_include('client.inc', 'ting');
//  //$xml = ting_cache_get($object_id . ':FULLTEXT');
//  if( !$xml ) {
//    $request = ting_get_request_factory()->getObjectRequest();
//    $request->setObjectId('150028:29310564');
//    $request->setProfile('ereol');
//    $request->setFormat('docbook');
//    $request->setObjectFormat('docbook');
//    $request->setOutputType('xml');
//    $xml = ting_execute($request);
//    ting_cache_set($object_id . ':FULLTEXT', $xml);
//  }
//  return $xml;
}